### ISSUE TITLE
a few issues / suggestions

### ISSUE THREAD

**Issue by KeLaiFu** [Keruon/PB-clone#3]
I've just built the module, and while it doesn't work on first try, I noticed an issue with the size and placement of the PCB, in relation to the panel. In my DIY case, the lower part of the main PCB sits too low to allow it to be mounted on my rails. Admittedly my rails are not standard size, but this is the first module that has this problem so maybe there are some spacing guidelines on clearance. There's definitely some room to shunt the lower row of jacks up 4 or 5mm. 
Still, thanks for the great work and I'll hopefully troubleshoot this one and look at making some adjustments to my case in future.

**Comment by Keruon** [comment]
I just verified the measurements and yes, it's slightly too tall for regular thick rail rack. 
Forums suggest ( https://www.muffwiggler.com/forum/viewtopic.php?t=203897 ) that you should use 110mm as max height and my pcb is 116mm. I've used niftycase as the build template and as it has slim rails where you can fit "fat" modules.

I'll do a rev3 board with reduced height, like you suggested, the jacks have room to move inwards.
